const std = @import("std");
const json = std.json;

const pkmn = @import("pkmn");
const Species = pkmn.gen1.Species;
const Move = pkmn.gen1.Move;

pub var player_imports: std.ArrayList(PokemonImport) = undefined;
pub var enemy_imports: std.ArrayList(PokemonImport) = undefined;

pub const PokemonImport = struct {
    species: []const u8,
    dvs: struct { // Can't parse a JSON with less than 8 bits SMH
        atk: u8,
        def: u8,
        spc: u8,
        spe: u8,
    },
    evs: struct {
        hp: u8,
        atk: u8,
        def: u8,
        spc: u8,
        spe: u8,
    },
    moves: [4][]const u8,
};

pub fn convert_species(species: []const u8) ?Species {
    const string_to_enum = std.StaticStringMap(Species).initComptime(.{
        .{ "", Species.None },
        .{ "Bulbasaur", Species.Bulbasaur },
        .{ "Ivysaur", Species.Ivysaur },
        .{ "Venusaur", Species.Venusaur },
        .{ "Charmander", Species.Charmander },
        .{ "Charmeleon", Species.Charmeleon },
        .{ "Charizard", Species.Charizard },
        .{ "Squirtle", Species.Squirtle },
        .{ "Wartortle", Species.Wartortle },
        .{ "Blastoise", Species.Blastoise },
        .{ "Caterpie", Species.Caterpie },
        .{ "Metapod", Species.Metapod },
        .{ "Butterfree", Species.Butterfree },
        .{ "Weedle", Species.Weedle },
        .{ "Kakuna", Species.Kakuna },
        .{ "Beedrill", Species.Beedrill },
        .{ "Pidgey", Species.Pidgey },
        .{ "Pidgeotto", Species.Pidgeotto },
        .{ "Pidgeot", Species.Pidgeot },
        .{ "Rattata", Species.Rattata },
        .{ "Raticate", Species.Raticate },
        .{ "Spearow", Species.Spearow },
        .{ "Fearow", Species.Fearow },
        .{ "Ekans", Species.Ekans },
        .{ "Arbok", Species.Arbok },
        .{ "Pikachu", Species.Pikachu },
        .{ "Raichu", Species.Raichu },
        .{ "Sandshrew", Species.Sandshrew },
        .{ "Sandslash", Species.Sandslash },
        .{ "NidoranF", Species.NidoranF },
        .{ "Nidorina", Species.Nidorina },
        .{ "Nidoqueen", Species.Nidoqueen },
        .{ "NidoranM", Species.NidoranM },
        .{ "Nidorino", Species.Nidorino },
        .{ "Nidoking", Species.Nidoking },
        .{ "Clefairy", Species.Clefairy },
        .{ "Clefable", Species.Clefable },
        .{ "Vulpix", Species.Vulpix },
        .{ "Ninetales", Species.Ninetales },
        .{ "Jigglypuff", Species.Jigglypuff },
        .{ "Wigglytuff", Species.Wigglytuff },
        .{ "Zubat", Species.Zubat },
        .{ "Golbat", Species.Golbat },
        .{ "Oddish", Species.Oddish },
        .{ "Gloom", Species.Gloom },
        .{ "Vileplume", Species.Vileplume },
        .{ "Paras", Species.Paras },
        .{ "Parasect", Species.Parasect },
        .{ "Venonat", Species.Venonat },
        .{ "Venomoth", Species.Venomoth },
        .{ "Diglett", Species.Diglett },
        .{ "Dugtrio", Species.Dugtrio },
        .{ "Meowth", Species.Meowth },
        .{ "Persian", Species.Persian },
        .{ "Psyduck", Species.Psyduck },
        .{ "Golduck", Species.Golduck },
        .{ "Mankey", Species.Mankey },
        .{ "Primeape", Species.Primeape },
        .{ "Growlithe", Species.Growlithe },
        .{ "Arcanine", Species.Arcanine },
        .{ "Poliwag", Species.Poliwag },
        .{ "Poliwhirl", Species.Poliwhirl },
        .{ "Poliwrath", Species.Poliwrath },
        .{ "Abra", Species.Abra },
        .{ "Kadabra", Species.Kadabra },
        .{ "Alakazam", Species.Alakazam },
        .{ "Machop", Species.Machop },
        .{ "Machoke", Species.Machoke },
        .{ "Machamp", Species.Machamp },
        .{ "Bellsprout", Species.Bellsprout },
        .{ "Weepinbell", Species.Weepinbell },
        .{ "Victreebel", Species.Victreebel },
        .{ "Tentacool", Species.Tentacool },
        .{ "Tentacruel", Species.Tentacruel },
        .{ "Geodude", Species.Geodude },
        .{ "Graveler", Species.Graveler },
        .{ "Golem", Species.Golem },
        .{ "Ponyta", Species.Ponyta },
        .{ "Rapidash", Species.Rapidash },
        .{ "Slowpoke", Species.Slowpoke },
        .{ "Slowbro", Species.Slowbro },
        .{ "Magnemite", Species.Magnemite },
        .{ "Magneton", Species.Magneton },
        .{ "Farfetchd", Species.Farfetchd },
        .{ "Doduo", Species.Doduo },
        .{ "Dodrio", Species.Dodrio },
        .{ "Seel", Species.Seel },
        .{ "Dewgong", Species.Dewgong },
        .{ "Grimer", Species.Grimer },
        .{ "Muk", Species.Muk },
        .{ "Shellder", Species.Shellder },
        .{ "Cloyster", Species.Cloyster },
        .{ "Gastly", Species.Gastly },
        .{ "Haunter", Species.Haunter },
        .{ "Gengar", Species.Gengar },
        .{ "Onix", Species.Onix },
        .{ "Drowzee", Species.Drowzee },
        .{ "Hypno", Species.Hypno },
        .{ "Krabby", Species.Krabby },
        .{ "Kingler", Species.Kingler },
        .{ "Voltorb", Species.Voltorb },
        .{ "Electrode", Species.Electrode },
        .{ "Exeggcute", Species.Exeggcute },
        .{ "Exeggutor", Species.Exeggutor },
        .{ "Cubone", Species.Cubone },
        .{ "Marowak", Species.Marowak },
        .{ "Hitmonlee", Species.Hitmonlee },
        .{ "Hitmonchan", Species.Hitmonchan },
        .{ "Lickitung", Species.Lickitung },
        .{ "Koffing", Species.Koffing },
        .{ "Weezing", Species.Weezing },
        .{ "Rhyhorn", Species.Rhyhorn },
        .{ "Rhydon", Species.Rhydon },
        .{ "Chansey", Species.Chansey },
        .{ "Tangela", Species.Tangela },
        .{ "Kangaskhan", Species.Kangaskhan },
        .{ "Horsea", Species.Horsea },
        .{ "Seadra", Species.Seadra },
        .{ "Goldeen", Species.Goldeen },
        .{ "Seaking", Species.Seaking },
        .{ "Staryu", Species.Staryu },
        .{ "Starmie", Species.Starmie },
        .{ "MrMime", Species.MrMime },
        .{ "Scyther", Species.Scyther },
        .{ "Jynx", Species.Jynx },
        .{ "Electabuzz", Species.Electabuzz },
        .{ "Magmar", Species.Magmar },
        .{ "Pinsir", Species.Pinsir },
        .{ "Tauros", Species.Tauros },
        .{ "Magikarp", Species.Magikarp },
        .{ "Gyarados", Species.Gyarados },
        .{ "Lapras", Species.Lapras },
        .{ "Ditto", Species.Ditto },
        .{ "Eevee", Species.Eevee },
        .{ "Vaporeon", Species.Vaporeon },
        .{ "Jolteon", Species.Jolteon },
        .{ "Flareon", Species.Flareon },
        .{ "Porygon", Species.Porygon },
        .{ "Omanyte", Species.Omanyte },
        .{ "Omastar", Species.Omastar },
        .{ "Kabuto", Species.Kabuto },
        .{ "Kabutops", Species.Kabutops },
        .{ "Aerodactyl", Species.Aerodactyl },
        .{ "Snorlax", Species.Snorlax },
        .{ "Articuno", Species.Articuno },
        .{ "Zapdos", Species.Zapdos },
        .{ "Moltres", Species.Moltres },
        .{ "Dratini", Species.Dratini },
        .{ "Dragonair", Species.Dragonair },
        .{ "Dragonite", Species.Dragonite },
        .{ "Mewtwo", Species.Mewtwo },
        .{ "Mew", Species.Mew },
    });

    return string_to_enum.get(species);
}

pub fn convert_move(move: []const u8) ?Move {
    const string_to_enum = std.StaticStringMap(Move).initComptime(.{
        .{ "", Move.None },
        .{ "Pound", Move.Pound },
        .{ "Karate Chop", Move.KarateChop },
        .{ "Double Slap", Move.DoubleSlap },
        .{ "Comet Punch", Move.CometPunch },
        .{ "Mega Punch", Move.MegaPunch },
        .{ "Pay Day", Move.PayDay },
        .{ "Fire Punch", Move.FirePunch },
        .{ "Ice Punch", Move.IcePunch },
        .{ "Thunder Punch", Move.ThunderPunch },
        .{ "Scratch", Move.Scratch },
        .{ "Vise Grip", Move.ViseGrip },
        .{ "Guillotine", Move.Guillotine },
        .{ "Razor Wind", Move.RazorWind },
        .{ "Swords Dance", Move.SwordsDance },
        .{ "Cut", Move.Cut },
        .{ "Gust", Move.Gust },
        .{ "Wing Attack", Move.WingAttack },
        .{ "Whirlwind", Move.Whirlwind },
        .{ "Fly", Move.Fly },
        .{ "Bind", Move.Bind },
        .{ "Slam", Move.Slam },
        .{ "Vine Whip", Move.VineWhip },
        .{ "Stomp", Move.Stomp },
        .{ "Double Kick", Move.DoubleKick },
        .{ "Mega Kick", Move.MegaKick },
        .{ "Jump Kick", Move.JumpKick },
        .{ "Rolling Kick", Move.RollingKick },
        .{ "Sand Attack", Move.SandAttack },
        .{ "Headbutt", Move.Headbutt },
        .{ "Horn Attack", Move.HornAttack },
        .{ "Fury Attack", Move.FuryAttack },
        .{ "Horn Drill", Move.HornDrill },
        .{ "Tackle", Move.Tackle },
        .{ "Body Slam", Move.BodySlam },
        .{ "Wrap", Move.Wrap },
        .{ "Take Down", Move.TakeDown },
        .{ "Thrash", Move.Thrash },
        .{ "Double Edge", Move.DoubleEdge },
        .{ "Tail Whip", Move.TailWhip },
        .{ "Poison Sting", Move.PoisonSting },
        .{ "Twineedle", Move.Twineedle },
        .{ "Pin Missile", Move.PinMissile },
        .{ "Leer", Move.Leer },
        .{ "Bite", Move.Bite },
        .{ "Growl", Move.Growl },
        .{ "Roar", Move.Roar },
        .{ "Sing", Move.Sing },
        .{ "Supersonic", Move.Supersonic },
        .{ "Sonic Boom", Move.SonicBoom },
        .{ "Disable", Move.Disable },
        .{ "Acid", Move.Acid },
        .{ "Ember", Move.Ember },
        .{ "Flamethrower", Move.Flamethrower },
        .{ "Mist", Move.Mist },
        .{ "Water Gun", Move.WaterGun },
        .{ "Hydro Pump", Move.HydroPump },
        .{ "Surf", Move.Surf },
        .{ "Ice Beam", Move.IceBeam },
        .{ "Blizzard", Move.Blizzard },
        .{ "Psybeam", Move.Psybeam },
        .{ "Bubble Beam", Move.BubbleBeam },
        .{ "Aurora Beam", Move.AuroraBeam },
        .{ "Hyper Beam", Move.HyperBeam },
        .{ "Peck", Move.Peck },
        .{ "Drill Peck", Move.DrillPeck },
        .{ "Submission", Move.Submission },
        .{ "Low Kick", Move.LowKick },
        .{ "Counter", Move.Counter },
        .{ "Seismic Toss", Move.SeismicToss },
        .{ "Strength", Move.Strength },
        .{ "Absorb", Move.Absorb },
        .{ "Mega Drain", Move.MegaDrain },
        .{ "Leech Seed", Move.LeechSeed },
        .{ "Growth", Move.Growth },
        .{ "Razor Leaf", Move.RazorLeaf },
        .{ "SolarBeam", Move.SolarBeam },
        .{ "Poison Powder", Move.PoisonPowder },
        .{ "Stun Spore", Move.StunSpore },
        .{ "Sleep Powder", Move.SleepPowder },
        .{ "Petal Dance", Move.PetalDance },
        .{ "String Shot", Move.StringShot },
        .{ "Dragon Rage", Move.DragonRage },
        .{ "Fire Spin", Move.FireSpin },
        .{ "Thunder Shock", Move.ThunderShock },
        .{ "Thunderbolt", Move.Thunderbolt },
        .{ "Thunder Wave", Move.ThunderWave },
        .{ "Thunder", Move.Thunder },
        .{ "Rock Throw", Move.RockThrow },
        .{ "Earthquake", Move.Earthquake },
        .{ "Fissure", Move.Fissure },
        .{ "Dig", Move.Dig },
        .{ "Toxic", Move.Toxic },
        .{ "Confusion", Move.Confusion },
        .{ "Psychic", Move.Psychic },
        .{ "Hypnosis", Move.Hypnosis },
        .{ "Meditate", Move.Meditate },
        .{ "Agility", Move.Agility },
        .{ "Quick Attack", Move.QuickAttack },
        .{ "Rage", Move.Rage },
        .{ "Teleport", Move.Teleport },
        .{ "Night Shade", Move.NightShade },
        .{ "Mimic", Move.Mimic },
        .{ "Screech", Move.Screech },
        .{ "Double Team", Move.DoubleTeam },
        .{ "Recover", Move.Recover },
        .{ "Harden", Move.Harden },
        .{ "Minimize", Move.Minimize },
        .{ "Smokescreen", Move.Smokescreen },
        .{ "Confuse Ray", Move.ConfuseRay },
        .{ "Withdraw", Move.Withdraw },
        .{ "Defense Curl", Move.DefenseCurl },
        .{ "Barrier", Move.Barrier },
        .{ "Light Screen", Move.LightScreen },
        .{ "Haze", Move.Haze },
        .{ "Reflect", Move.Reflect },
        .{ "Focus Energy", Move.FocusEnergy },
        .{ "Bide", Move.Bide },
        .{ "Metronome", Move.Metronome },
        .{ "Mirror Move", Move.MirrorMove },
        .{ "Self Destruct", Move.SelfDestruct },
        .{ "Egg Bomb", Move.EggBomb },
        .{ "Lick", Move.Lick },
        .{ "Smog", Move.Smog },
        .{ "Sludge", Move.Sludge },
        .{ "Bone Club", Move.BoneClub },
        .{ "Fire Blast", Move.FireBlast },
        .{ "Waterfall", Move.Waterfall },
        .{ "Clamp", Move.Clamp },
        .{ "Swift", Move.Swift },
        .{ "Skull Bash", Move.SkullBash },
        .{ "Spike Cannon", Move.SpikeCannon },
        .{ "Constrict", Move.Constrict },
        .{ "Amnesia", Move.Amnesia },
        .{ "Kinesis", Move.Kinesis },
        .{ "Soft Boiled", Move.SoftBoiled },
        .{ "High Jump Kick", Move.HighJumpKick },
        .{ "Glare", Move.Glare },
        .{ "Dream Eater", Move.DreamEater },
        .{ "Poison Gas", Move.PoisonGas },
        .{ "Barrage", Move.Barrage },
        .{ "Leech Life", Move.LeechLife },
        .{ "Lovely Kiss", Move.LovelyKiss },
        .{ "Sky Attack", Move.SkyAttack },
        .{ "Transform", Move.Transform },
        .{ "Bubble", Move.Bubble },
        .{ "Dizzy Punch", Move.DizzyPunch },
        .{ "Spore", Move.Spore },
        .{ "Flash", Move.Flash },
        .{ "Psywave", Move.Psywave },
        .{ "Splash", Move.Splash },
        .{ "Acid Armor", Move.AcidArmor },
        .{ "Crabhammer", Move.Crabhammer },
        .{ "Explosion", Move.Explosion },
        .{ "Fury Swipes", Move.FurySwipes },
        .{ "Bonemerang", Move.Bonemerang },
        .{ "Rest", Move.Rest },
        .{ "Rock Slide", Move.RockSlide },
        .{ "Hyper Fang", Move.HyperFang },
        .{ "Sharpen", Move.Sharpen },
        .{ "Conversion", Move.Conversion },
        .{ "Tri Attack", Move.TriAttack },
        .{ "Super Fang", Move.SuperFang },
        .{ "Slash", Move.Slash },
        .{ "Substitute", Move.Substitute },
        .{ "Struggle", Move.Struggle },
    });

    return string_to_enum.get(move);
}
